config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'students', to: 'students#index'
  get 'instructors', to: 'instructors#index'
  get 'courses', to: 'courses#index'
  get 'cohorts', to: 'cohorts#index'
  get 'principal/index'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :index
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  resources :principal
  resources :sessions, only: [:create]
  resources :users

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :instructor, optional: true
  has_and_belongs_to_many :students

  validates :name, length: { minimum: 2, maximum: 16 }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord

end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, length: { minimum: 2, maximum: 32 }
  validates :hours, inclusion: { in: 30...9999 }
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :first_name, length: {minimum: 2, maximum: 16}
  validates :last_name, length: {minimum: 2, maximum: 16}
  validates :age, inclusion: { in: 21...99 }
  validates :salary, inclusion: { in: 40000...700000 }
  validates :education, presence: true

  has_many :cohorts
end

app/models/page.rb
class Page < ApplicationRecord
  end

app/models/principal.rb
class Principal < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, length: {minimum: 2, maximum: 16}
    validates :last_name, length: {minimum: 2, maximum: 16}
    validates :age, inclusion: { in: 15...99 }
    validates :education, presence: true
    has_and_belongs_to_many :cohorts


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def edit
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def show
    @student = Student.find(params[:id])
  end

  def create
    @student = Student.new(params.require(:student).permit(:first_name, :last_name, :age, :education))
    if @student.save
      redirect_to @student
    else
      errors = @student.errors.full_messages
      flash.now[:error] = errors
      render 'new'
    end
 end

  def update
    @student = Student.find(params[:id])

    if @student.update(params.require(:student).permit(:first_name, :last_name, :email, :age, :education))
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'STUDENT SUCCESSFULLY DELETED' }
      format.js { render layout: false }
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/destroy.js.erb
$('.delete_student').bind('ajax:success', function() {
   $(this).closest('div').fadeOut();
});

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= form_with(model: @student, local: true) do |f| %>

<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name"%><br>
<%= f.number_field :age, placeholder: "Age" %><br>
<%= f.select :education, ['HS', 'College', 'Masters', 'PHD'], :include_blank => true %><br><br>

<%= f.submit 'Edit Student' %>

<% end %>

<div class="buttons"><br><br>
  <%= link_to 'List', students_path %>
  <%= link_to 'Create a Student', new_student_path %>
  <%= link_to 'Delete', student_path, data: {:confirm => 'Are you sure?'}, :method => :delete %>
</div>

app/views/students/index.html.erb
<h1>Students</h1>
<div class="divTable">
  <div class="divTableBody">
    <div class="divTableRow">
      <div class="divTableHead" style="width: 150px">First Name</div>
      <div class="divTableHead" style="width: 150px">Last Name</div>
      <div class="divTableHead">Age</div>
      <div class="divTableHead">Education</div>
    </div>
    <% @students.each do |student| %>
      <div class="divTableRow">
        <div class="divTableCell" style="width: 150px"><a href="/students/<%= student.id %>"><%= student.first_name %></a></div>
        <div class="divTableCell" style="width: 150px"><a href="/students/<%= student.id %>"><%= student.last_name %></a></div>
        <div class="divTableCell"><%= student.age %></div>
        <div class="divTableCell"><%= student.education %></div>
      </div>
    <% end %>
    <div class="buttons"><br><br>
      <%= link_to 'Create a Student', new_student_path %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<h1>Add New Student</h1>

<%= form_for(@student) do |f| %>

<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name"%><br>
<%= f.number_field :age, placeholder: "Age" %><br>
<%= f.select :education, ['HS', 'College', 'Masters', 'PHD'], :include_blank => true %><br>

<%= f.submit 'Add a Student' %><br>
<% end %>

<div class="buttons"><br><br>
  <%= link_to 'List', students_path %>
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section-header">
  <h3>Student Info</h3>
</div>

<p>
  <strong>First Name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Education:</strong>
  <%= @student.education %>
</p>

<div class="buttons"><br><br>
  <%= link_to 'List', students_path %>
  <%= link_to 'Create a Student', new_student_path %>
  <%= link_to 'Edit', edit_student_path %>
  <%= link_to 'Delete', student_path(@student), data: {:confirm => 'Are you sure?'}, :method => :delete , 
  :remote => true, :class => 'delete_student' %>
</div>