config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'students', to: 'students#index'
  get 'instructors', to: 'instructors#index'
  get 'courses', to: 'courses#index'
  get 'cohorts', to: 'cohorts#index'
  get 'principal/index'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :index
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  resources :principal
  resources :sessions, only: [:create]
  resources :users

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :instructor, optional: true
  has_and_belongs_to_many :students

  validates :name, length: { minimum: 2, maximum: 16 }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord

end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, length: { minimum: 2, maximum: 32 }
  validates :hours, inclusion: { in: 30...9999 }
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :first_name, length: {minimum: 2, maximum: 16}
  validates :last_name, length: {minimum: 2, maximum: 16}
  validates :age, inclusion: { in: 21...99 }
  validates :salary, inclusion: { in: 40000...700000 }
  validates :education, presence: true

  has_many :cohorts
end

app/models/page.rb
class Page < ApplicationRecord
  end

app/models/principal.rb
class Principal < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, length: {minimum: 2, maximum: 16}
    validates :last_name, length: {minimum: 2, maximum: 16}
    validates :age, inclusion: { in: 15...99 }
    validates :education, presence: true
    has_and_belongs_to_many :cohorts


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def create
    @instructor = Instructor.new(params.require(:instructor).permit(:first_name, :last_name, :age, :salary, :education))
    if @instructor.save
      redirect_to @instructor
    else
      errors = @instructor.errors.full_messages
      flash.now[:error] = errors
      render 'new'
    end
 end

  def update
    @instructor = Instructor.find(params[:id])

    if @instructor.update(params.require(:instructor).permit(:first_name, :last_name, :email, :age, :salary, :education))
      redirect_to @instructor
    else
      render 'edit'
    end
  end




  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'INSTRUCTOR SUCCESSFULLY DELETED' }
      format.js { render layout: false }
  end

  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instructors/destroy.js.erb
$('.delete_instructor').bind('ajax:success', function() {
   $(this).closest('div').fadeOut();
});

app/views/instructors/edit.html.erb
<h1>Edit Instructor</h1>

<%= form_with(model: @instructor, local: true) do |f| %>

<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name"%><br>
<%= f.number_field :age, placeholder: "Age" %><br>
<%= f.number_field :salary, placeholder: "Salary" %><br>
<%= f.select :education, ['HS', 'College', 'Masters', 'PHD'], :include_blank => true %><br><br>

<%= f.submit 'Edit Instructor' %><br>
<% end %>

<div class="buttons"><br><br>
  <%= link_to 'List', instructors_path %>
  <%= link_to 'Create an Instructor', new_instructor_path %>
  <%= link_to 'Delete', instructor_path, data: {:confirm => 'Are you sure?'}, :method => :delete %>
</div>

app/views/instructors/index.html.erb
<h1>Instructors</h1>
<div class="divTable">
  <div class="divTableBody">
    <div class="divTableRow">
      <div class="divTableHead" style="width: 150px">First Name</div>
      <div class="divTableHead" style="width: 150px">Last Name</div>
      <div class="divTableHead">Age</div>
      <div class="divTableHead">Salary</div>
      <div class="divTableHead">Education</div>
    </div>
  <% @instructors.each do |instructor| %>
      <div class="divTableRow">
        <div class="divTableCell" style="width: 150px"><a href="/instructors/<%= instructor.id %>"><%= instructor.first_name %></a></div>
        <div class="divTableCell" style="width: 150px"><a href="/instructors/<%= instructor.id %>"><%= instructor.last_name %></a></div>
        <div class="divTableCell"><%= instructor.age %></div>
          <div class="divTableCell"><%= instructor.salary %></div>
        <div class="divTableCell"><%= instructor.education %></div>
      </div>
    <% end %>
    <div class="buttons"><br><br>
      <%= link_to 'Create an Instructor', new_instructor_path %>
    </div>
  </div>
</div>

app/views/instructors/new.html.erb
<h1>Add New Instructor</h1>

<%= form_for(@instructor) do |f| %>

<%= f.text_field :first_name, placeholder: "First Name" %><br>
<%= f.text_field :last_name, placeholder: "Last Name"%><br>
<%= f.number_field :age, placeholder: "Age" %><br>
<%= f.number_field :salary, placeholder: "Salary" %><br>
<%= f.select :education, ['HS', 'College', 'Masters', 'PHD'], :include_blank => true %><br>

<%= f.submit 'Add an Instructor' %><br>
<% end %>

<div class="buttons"><br><br>
  <%= link_to 'List', instructors_path %>
</div>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="section-header">
  <h1>Instructors Info</h1>
</div>

<p>
  <strong>First Name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @instructor.age %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @instructor.salary%>
</p>

<p>
  <strong>Education:</strong>
  <%= @instructor.education %>
</p>

<div class="buttons"><br><br>
  <%= link_to 'List', instructors_path %>
  <%= link_to 'Create an Instructor', new_instructor_path %>
  <%= link_to 'Edit', edit_instructor_path %>
  <%= link_to 'Delete', instructor_path(@instructor), data: {:confirm => 'Are you sure?'}, :method => :delete ,
  :remote => true, :class => 'delete_instructor' %>
</div>