config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'students', to: 'students#index'
  get 'instructors', to: 'instructors#index'
  get 'courses', to: 'courses#index'
  get 'cohorts', to: 'cohorts#index'
  get 'principal/index'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :index
  resources :students
  resources :instructors
  resources :courses
  resources :cohorts
  resources :principal
  resources :sessions, only: [:create]
  resources :users

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course, optional: true
  belongs_to :instructor, optional: true
  has_and_belongs_to_many :students

  validates :name, length: { minimum: 2, maximum: 16 }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/cohort_student.rb
class CohortStudent < ApplicationRecord

end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, length: { minimum: 2, maximum: 32 }
  validates :hours, inclusion: { in: 30...9999 }
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  validates :first_name, length: {minimum: 2, maximum: 16}
  validates :last_name, length: {minimum: 2, maximum: 16}
  validates :age, inclusion: { in: 21...99 }
  validates :salary, inclusion: { in: 40000...700000 }
  validates :education, presence: true

  has_many :cohorts
end

app/models/page.rb
class Page < ApplicationRecord
  end

app/models/principal.rb
class Principal < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
    validates :first_name, length: {minimum: 2, maximum: 16}
    validates :last_name, length: {minimum: 2, maximum: 16}
    validates :age, inclusion: { in: 15...99 }
    validates :education, presence: true
    has_and_belongs_to_many :cohorts


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true, presence: true
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/cohort_helper.rb
module CohortHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrufrockAcademy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>


      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


  <div class="admin">
    <header class="adminheader">
      <a href="#" class="symbolheader">
        <!-- <h1>ADMIN PANEL</h1> -->
                <% if @user %>
           <%= link_to "LOGOUT", logout_path(@user)%>

          <% end %>

      </a>
      <div class="toolbar">

      </div>
    </header>
    <nav class="adminnav">

      <ul class="sidebar">
        <li class="sidebar__item">
          <a class="sidebar__link" href="/">Home</a>
        </li>
        <li class="sidebar__item">
          <%= link_to 'STUDENTS', students_path, :class => "sidebar__link" %>
        </li>
        <li class="sidebar__item">
          <%= link_to 'INSTRUCTORS', instructors_path, :class => "sidebar__link" %>
        </li>
      <li class="sidebar__item">
        <%= link_to 'COHORTS', cohorts_path, :class => "sidebar__link" %>
        <li class="sidebar__item">
          <%= link_to 'COURSES', courses_path, :class => "sidebar__link" %>
        </li>
        <li class="sidebar__item">
          <%= link_to 'PRINCIPAL', "principal/index", :class => "sidebar__link" %>

        </li>
      </ul>
    </nav>
    <div class="adminmain">
      <%= yield %>

    </div>
    <footer class="adminfooter">
      <span>
        &copy; 2018 Prufrock Prepatory Academy
      </span>
    </footer>
  </div>



</body>
</html>

app/views/pages/cohorts.html.erb
<h1>Pages#cohorts</h1>
<p>Find me in app/views/pages/cohorts.html.erb</p>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrufrockAcademy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


<div id="headerbar">



  <div class="logo"><img src="/images/logo.png">
  </div>
</div>
<div id="navbar">
  <ul>
       <% if @user %>
           <li> <%= link_to "LOGOUT", logout_path(@user)%>
</li>
          <% end %>
      <li><a href="/">HOME</a></li>


    <li><%= link_to 'STUDENTS', students_path %></li>
    <li><%= link_to 'INSTRUCTORS', instructors_path %></li>
    <li><%= link_to 'COHORTS', cohorts_path %></li>
    <li><%= link_to 'COURSES', courses_path %></li>
    <li><%= link_to 'PRINCIPAL', "principal/index" %></li>
  </ul>
</div>
<div class="slogan">
  <!-- <div class="lion"><img src="/images/lion.png"></div> -->
  <div  class="Prufrock"> <br><h1>PRUFROCK PREPATORY<br>SCHOOL</h1>
</div>
<div class="login">


<%- if flash[:error] %>
  <%= flash[:error] %>
<% elsif flash[:success] %>
  <%= flash[:success] %>
<% end %>


<% if @user.nil? %>


<%= form_for :session, url: sessions_path do |f| %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>


    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %><br><br>


    <%= f.submit 'Log In', class: 'btn btn-primary' %>

      <%= link_to 'Click here to create an account.', new_user_path %>

<% end %>

<% end %>


</div>
</div>
<div class="school carousel">
  <img class="active" src="/images/school.jpg">
  <img src="/images/bus.jpeg">
  <img src="/images/classroom.jpg">
  <img src="/images/students.jpg">
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


</body>
</html>